# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
language: swift
osx_image: xcode9
branches:
  only:
    - master

script: xcodebuild -workspace "Example/NXMActionSheet.xcworkspace" -scheme "NXMActionSheet-Example" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
pod lib lint;